version: 2
jobs:
  check_version:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: make check-version
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - check_version:
          filters:
            branches:
              ignore: master
